# frozen_string_literal: true

source "https://rubygems.org"

# This Gemfile is part of the honeypot decoy CI runner.
# It mimics a typical GitLab CI runner environment.

ruby ">= 3.1.0"

gem "sinatra", "~> 3.1"
gem "puma", "~> 6.4"
gem "rack", "~> 3.0"
gem "json", "~> 2.7"

group :development, :test do
  gem "rspec", "~> 3.13"
  gem "rack-test", "~> 2.1"
  gem "rubocop", "~> 1.62"
end
