# frozen_string_literal: true

source "https://rubygems.org"

# This Gemfile is part of the honeypot decoy Rails application.
# It mimics a typical Rails app to appear authentic to attackers.

ruby "3.2.2"

gem "rails", "~> 7.0.8"
gem "puma", "~> 6.4"
gem "pg", "~> 1.5"
gem "redis", "~> 5.0"
gem "sidekiq", "~> 7.2"
gem "devise", "~> 4.9"
gem "cancancan", "~> 3.5"
gem "jbuilder", "~> 2.11"
gem "bootsnap", require: false
gem "sprockets-rails"
gem "importmap-rails"
gem "turbo-rails"
gem "stimulus-rails"

group :development, :test do
  gem "debug", platforms: %i[mri windows]
  gem "rspec-rails", "~> 6.1"
  gem "factory_bot_rails"
end

group :development do
  gem "web-console"
  gem "rack-mini-profiler"
end
