# frozen_string_literal: true

source 'https://rubygems.org'

ruby '>= 3.0.0'

# FFI for native API bindings
gem 'ffi', '~> 1.16'

# Web framework (C2 server)
gem 'sinatra', '~> 4.0'
gem 'puma', '~> 6.4'

# Database
gem 'sqlite3', '~> 1.7'
gem 'sequel', '~> 5.75'

# HTTP
gem 'faraday', '~> 2.8'

# Encoding/Crypto
gem 'base64', '~> 0.2'
gem 'openssl', '~> 3.2'

# Logging
gem 'logger', '~> 1.6'

# Configuration
gem 'yaml'

group :test do
  gem 'rspec', '~> 3.13'
  gem 'webmock', '~> 3.19'
end
